### PR TITLE
Update WallOfFire.java

### PR DESCRIPTION
**Pull request by matanrak**
Added config option to change kockback

### CODE REVIEW

**Comment by OmniCypher-** [comment]
Few issues that need to be resolved:
1. Your build didn't compile because you are missing a parenthesis at the end of line 103
- entity.setVelocity(player.getLocation().getDirection().multiply(this.kockback);

2. The minor variable misspelling on lines 40, 56, and 103
- private double kockback;
- this.kockback = getConfig().getDouble("Abilities.Fire.WallOfFire.Knockback");
- entity.setVelocity(player.getLocation().getDirection().multiply(this.kockback);

3. You must add the variable "Knockback" to the Abilities.Fire.WallOfFire.Knockback path in ConfigManager.java for it to be added to the plugins config file

**Comment by phase** [comment]
For the love of god, **use an IDE**.

**Comment by matanrak** [comment]
I will!

Thank you and have a lovely day!
Matan.

**Comment by curz46** [comment]
@matarak are you working on this, or can it be closed?

**Comment by matanrak** [comment]
can be closed

**Pull request closed without merging**
