### PR TITLE
Update KingdomsX region detection

### PR DESCRIPTION
**Pull request by Leomelonseeds**
KingdomsX has once again broken support with ProjectKorra due to recent API changes. This update makes PK compatible with KingdomsX versions 1.14.15 and above, but breaks support for versions below that (I think). Some refactoring has also been done to improve performance and code readability.

### CODE REVIEW

**Review by StrangeOne101 — DISMISSED** [review]
As long as this is tested, I'm happy to approve. Thanks for the update 👍

**Comment by Leomelonseeds** [comment]
Just did some additional testing and fixed a few issues, thanks for your time.

**Review by StrangeOne101 — APPROVED** [review]
Took me a while to properly review it since I needed time to actually download kingdoms to view their API, but yeah, seems fine. Thanks for the PR

**Comment by StrangeOne101** [comment]
This unfortunately wasn't reviewed by other devs in time, and now is a little obsolete. Since:

1. Kingdoms has updated _again_ 
2. ProjectKorra is going to remove support for Kingdoms. Instead, Kingdoms is going to support PK.

We decided that this would be best as the Kingdoms dev is happy to add support for ProjectKorra. Instead of having to update our kingdoms support every time an update for Kingdoms comes out, the latest Kingdoms version will instead just support ProjectKorra with all the new changes they've made. This should solve most Kingdoms issues going forward

**Comment by ChristopherWMM** [comment]
Going to close this since we will likely be removing our kingdoms support implementations soon and this will no longer be relevant.

**Pull request closed without merging**
