### PR TITLE
Fix FireBlast going through liquids

### LINKED ISSUE #1098: Fix FireBlast going through liquids
The recent firebending refactor accidentally removed the FireBlast removal upon contact with liquids. Now FireBlast can travel through water and possibly lava, though I haven't tested the latter.
I've fixed this on my servers already, and I can make a PR that fixes this, but I think I need to rebase my fork before I do that, which is waiting on my current PR. There's no rush, though; I just wanted to make sure you were aware of the bug. I'll try making different branches in the future if that helps; sorry, I'm still pretty new to contributing on GitHub.

### PR DESCRIPTION
**Pull request by Aztlon**
## Fixes
- Fixed an issue with FireBlast in which it ignores water and lava blocks, passing through them
- Closes #1098

### CODE REVIEW

**Comment by ChristopherWMM** [comment]
Thanks for the PR @Aztlon, would you mind confirming that this same issue isn't happening with AirBlast or Charged FireBlast?

**Comment by Aztlon** [comment]
> Thanks for the PR @Aztlon, would you mind confirming that this same issue isn't happening with AirBlast or Charged FireBlast?

I can confirm this issue isn't happening with AirBlast or charged FireBlast.

**Review by ChristopherWMM — APPROVED** [review]
Awesome, thanks for checking. Looks good 👍

**Review by Varhagna — COMMENTED** [review]
Looks good!

**Review by Varhagna — APPROVED** [review]

**Pull request merged**
