### PR TITLE
Added possibility to change default particles of elements with addons!

### PR DESCRIPTION
**Pull request by Dreig-Michihi**
### This changes were tested on my server! Working great, supporting existing addons.
I made example addon, that adds ColorfulFire subelement, changes particles of airbending and adds my WaterSource particles.
**This PR's jar file:** https://github.com/Dreig-PSD/ProjectKorra/releases/tag/v1.10.2-FunctionalParticles
**Example addon:** https://github.com/Dreig-PSD/CustomBendingParticles/releases/tag/Updated1

## Additions
* Adds Functional.Particle FunctionalInterface, path: com.projectkorra.projectkorra.ability.functional
* A public variable of type Functional.Particle is used in classes FireAbility, AirAbility, WaterAbility ... XAbility as a default way to display particles of a certain element.
This variable is used in the XAbility#playXbendingParticles methods.
In addition, this variable is now also used in the FireComboStream class.

## Fixes
* SurgeWave and SurgeWall code did not use the WaterAbility#playFocusWaterEffect method, fixed.

## Removals
* Nothing is removed, some methods are marked as Deprecated with references in javadoc.

## Misc. Changes
* Methods like playXbendingSound, playXbendingParticles were moved to it's classes.
For example, FireAbility#playLightningbendingParticles was moved to LightningAbility, but FireAbility still have playLightningParticles method, but now it's depracated and just calls method from LightningAbility class.
* Deprecated methods were moved to the bottoms of the classes XAbility.

### CODE REVIEW

**Comment by Dreig-PSD** [comment]
https://github.com/Dreig-PSD/CustomBendingParticles/releases/tag/Example

**Review by StrangeOne101 — COMMENTED** [review]
I can't approve of this PR for a few reasons

1. You're formatting files to the point where we can't see the changes directly
2. This needs a bit more thought on the implementation. 

See discord conversations for more info.

**Review by Varhagna — CHANGES_REQUESTED** [review]
Please stick to the existing formatting style so we can better see what changes were actually made.

**Comment by ChristopherWMM** [comment]
This PR is not going to be accepted as is, the information it contains is good but somewhat obfuscated by the formatting changes. I am going to close this but it is worth investigating these ideas further.

**Pull request closed without merging**
