### PR TITLE
Fix passives not showing up in /b display

### PR DESCRIPTION
**Pull request by MKieburtz**
## Fixes
* Fixes https://github.com/ProjectKorra/ProjectKorra/issues/1169

image

### CODE REVIEW

**Review by Simplicitee — APPROVED** [review]

**Comment by ChristopherWMM** [comment]
> Shouldn't actually hidden passives still be hidden in display?

This was actually the initial flawed logic that led to the bug happening in the first place. Originally, we only made the change for combos. As I mentioned in the issue, all passive abilities are forcibly marked as hidden. Therefore, no passives will ever be shown 🤪

**Review by ChristopherWMM — APPROVED** [review]
Looks great! Thanks for your contribution! 👍

**Comment by Dooder07** [comment]
Should addon developers be able to make their passives hidden or should all passives just be visible no matter what?

**Comment by ChristopherWMM** [comment]
> Should addon developers be able to make their passives hidden or should all passives just be visible no matter what?

They are always forcibly hidden. This could be an area of later change, but for now, that is just how they are handled internally.

**Comment by Dooder07** [comment]
Ok sorry, that just had me pretty confused to be honest. I understand if it's intentional.

**Pull request merged**
