### PR TITLE
Update GeneralMethods.java

### PR DESCRIPTION
**Pull request by ReleasedSnow**
Added 'getLocationsAroundPoint' which takes a location and radius and returns a list of locations.

## Additions
* Adds 1.
    > GeneralMethods.getLocationsAroundPoint(Location location, int Radius)

### CODE REVIEW

**Comment by Slokx1** [comment]
what is the use for GeneralMethods#getLocationsAroundPoint ? what can it be used for

**Comment by StrangeOne101** [comment]
Sorry, but this is pointless _and_ inefficient

**Comment by Sammycocobear** [comment]
> Sorry, but this is pointless _and_ inefficient

ate

**Comment by Slokx1** [comment]
> Sorry, but this is pointless _and_ inefficient

8888

**Pull request closed without merging**
