### PR TITLE
Maven Redo

### PR DESCRIPTION
**Pull request by StrangeOne101**
## Changes
- Split ProjectKorra into 3 modules: core, core-legacy (1.16) and core-modern (1.20.4)
- Damage events and water bottle creation are split over the legacy and modern modules

Key things to see: 
- https://github.com/StrangeOne101/ProjectKorra/blob/1.11.3-final/core/src/com/projectkorra/projectkorra/util/DamageHandler.java#L217
- https://github.com/StrangeOne101/ProjectKorra/blob/1.11.3-final/core/src/com/projectkorra/projectkorra/waterbending/util/WaterReturn.java#L155

### CODE REVIEW

**Comment by PrideInt** [comment]
i see. so those ~200 files are just refactored?

**Review by PrideInt — COMMENTED** [review]
Is it possible to refactor `IBottleFinder.java` and `IDamageEventPasser.java` from core-legacy and core-modern into core and reference it in `DamageHandler.java` and `WaterReturn.java` from there? Or are they module specific?

**Comment by StrangeOne101** [comment]
> Is it possible to refactor `IBottleFinder.java` and `IDamageEventPasser.java` from core-legacy and core-modern into core and reference it in `DamageHandler.java` and `WaterReturn.java` from there? Or are they module specific?
The interfaces have to be in the core-legacy it core-modern modules and not core, since the core-legacy and core-modern modules don't access any core code.

But since both the modules are included in the core module, that module can access them


> I see. So those ~200 files are just refactored?

Correct. They are just relocated, with minor changes for the version specific stuff being the ones pointed out

**Comment by PrideInt** [comment]
> > Is it possible to refactor `IBottleFinder.java` and `IDamageEventPasser.java` from core-legacy and core-modern into core and reference it in `DamageHandler.java` and `WaterReturn.java` from there? Or are they module specific?
> 
> The interfaces have to be in the core-legacy it core-modern modules and not core, since the core-legacy and core-modern modules don't access any core code.
> 
> But since both the modules are included in the core module, the core module can access them
> 
> > I see. So those ~200 files are just refactored?
> 
> Correct. They are just relocated, with minor changes for the version specific stuff being the ones pointed out

I see. Thanks for clarifying.

**Review by PrideInt — APPROVED** [review]
Looks good to me.

**Comment by StrangeOne101** [comment]
It's a shame that GitHub doesn't show file relocations well. Thankfully, IntelliJ will still show you the right history for each part of the code, and not just "StrangeOne101 - Maven Redo" for everything lol

**Review by ChristopherWMM — APPROVED** [review]

**Pull request merged**
