### PR TITLE
Crucial typo fix

### PR DESCRIPTION
**Pull request by Chaotic-Dev**
ProjectKorra absolutely needs to verify its code before publishing or compiling it...

### CODE REVIEW

**Comment by Simplicitee** [comment]
"crucial"

**Comment by kingbirdy** [comment]
Squash commits before PRing

**Comment by nathank33** [comment]
kingbirdy is right, there is no reason to have those as two separate commits. Use git rebase to squash them into one.

**Comment by Chaotic-Dev** [comment]
Or you could squash them during merging.

**Comment by nathank33** [comment]
I found this for you!

http://lmgtfy.com/?q=how+to+squash+commits+with+git

**Pull request merged**
