### PR TITLE
Adding blocks to the world async is not allowed

### PR DESCRIPTION
**Pull request by PhanaticD**
Links to Appropriate Issue Reports Addressed in this Pull Request:
- Errors discovered on my own testing

Release Notes for this Pull Request:
- adding blocks async causes some bad problems

### CODE REVIEW

**Comment by OmniCypher-** [comment]
Can you elaborate a bit more on "adding blocks async causes some bad problems"? If this is a noteworthy issue we may need to look for other occurrences throughout the plugin.

**Comment by Spottedleaf** [comment]
Setting a block type can cause a chunk load. Attempting to do those asynchronously is a bad idea.

**Comment by PhanaticD** [comment]
http://bukkit.gamepedia.com/Scheduler_Programming#Tips_for_thread_safety

I personally had a crash (due to this method) when testing octopusform on my server without this commit within a few hours of adding it. Its been 2 days after making this commit and putting it on my server and no more crashes

**Comment by StrangeOne101** [comment]
Yeah, this should never have been called Async in the first place. Thanks for pointing that out, as yeah, nothing from Bukkit should be called async.

**Pull request merged**
