### PR TITLE
Fix ability bug with gamerule doDaylightCycle

### LINKED ISSUE #1084: doDaylightCycle gamerule interferes with abilities
CoreAbility's getStartTick() and getCurrentTick() will not function as intended when the doDaylightCycle gamerule is set to false.
This is a result of them using World::getFullTime.

### PR DESCRIPTION
**Pull request by PrimordialMoros**
Small bugfix for abilities' running ticks.
Method signatures (getStartTick and getCurrentTick) have remained the same to maintain compatibility (even though CoreAbility::getStartTick is unnecessary).
##  Fixes
* Fixes #1084

### CODE REVIEW

**Comment by PrimordialMoros** [comment]
Originally they had been implemented as a way to validate collisions (this has since changed and are no longer required for it). Their function however was to essentially measure the amount of times an ability had progressed. Incrementing the counter manually is perfectly valid for that purpose. It's quite useful in scenarios when you want to skip certain parts in the progress method of an ability (such as checking a heavy condition every x ticks instead).
As for removing the getStartTick method, it'd be better to mark it as deprecated instead. Can then remove it at a future version.

**Comment by Varhagna** [comment]
> Originally they had been implemented as a way to validate collisions (this has since changed and are no longer required for it). Their function however was to essentially measure the amount of times an ability had progressed. Incrementing the counter manually is perfectly valid for that purpose. It's quite useful in scenarios when you want to skip certain parts in the progress method of an ability (such as checking a heavy condition every x ticks instead).
> As for removing the getStartTick method, it'd be better to mark it as deprecated instead. Can then remove it at a future version.

Implementing the counter manually is valid yes, however its not valid when absolutely zero classes use this functionality. Its storing extra information than necessary for what is supposed to be a generalized version of an ability.

**Comment by ChristopherWMM** [comment]
Looks good, only other thing that might help clear this up and address both issues would be to make getCurrentTick static and then add a new instance method called getLifetime or something to return the lifetime of the ability in ticks.

**Comment by PrimordialMoros** [comment]
> Looks good, only other thing that might help clear this up and address both issues would be to make getCurrentTick static and then add a new instance method called getLifetime or something to return the lifetime of the ability in ticks.

The whole point is to avoid using World::getFullTime since it's not working as intended when the gamerule is set.
Providing that through a CoreAbility static method would be completely unnecessary and serves no purpose. I don't see why anyone would use that when they can simply call getFullTime themselves.

**Comment by ChristopherWMM** [comment]
..? 
```java
// Old method
public long getStartTick() {
	return this.startTick;
}

// New method set to be static
public static long getCurrentTick() {
	return currentTick;
}

// new method
public long getTickLifetime() {
	return currentTick - this.startTick;
}
```

> Providing that through a CoreAbility static method would be completely unnecessary and serves no purpose.

That is exactly why we could make the implementation static. It makes it easier to access (as it is static data) and follows the exact purpose of this PR.

> I don't see why anyone would use that when they can simply call getFullTime themselves.

Because

> The whole point is to avoid using World::getFullTime since it's not working as intended when the gamerule is set.

**Comment by PrimordialMoros** [comment]
Thanks for clearing up what you meant. Added the helper method to subtract the ticks even though I still consider it redundant.

**Review by Simplicitee — APPROVED** [review]

**Pull request merged**
