### PR TITLE
PhaseChange now updates the state of Snowable blocks once melted

### PR DESCRIPTION
**Pull request by Sammycocobear**
Addition:
- PhaseChange now updates the state of Snowable blocks once melted

Fixes:
- [https://github.com/ProjectKorra/ProjectKorra/issues/1215](url)

### CODE REVIEW

**Comment by StrangeOne101** [comment]
Is this tested? I feel like the non snowy property will remain even when the melting reverts. And if that is the case, you might have to do something about it from the TempBlock side

**Comment by Sammycocobear** [comment]
> Is this tested? I feel like the non snowy property will remain even when the melting reverts. And if that is the case, you might have to do something about it from the TempBlock side 

@StrangeOne101 Yes it is tested, and yes you are right. I'll whip smth up when I get a chance. Once the snow comes back it will not have the snow property

**Review by StrangeOne101 — APPROVED** [review]
Tested and works well 👍

**Review by ChristopherWMM — APPROVED** [review]
Awesome! Thanks @Sammycocobear!

**Pull request merged**
