### PR TITLE
Add permission check to /bending add <element> command

### PR DESCRIPTION
**Pull request by BeraTr1**
## Additions
*  /bending add <element/subelement> checks if the command sender has permission to add the element to the player (bending.command.add.<element/subelement>)

## Notes
* /bending add avatar will not 'force' add all elements to the player. Each element will still only apply if the command sender has the permission 'bending.command.add.<element/subelement>'

### CODE REVIEW

**Review by JustAHuman-xD — CHANGES_REQUESTED** [review]
I'd suggest abstracting that permission check as well as adding a check for `bending.command.add.*`
As I'm sure some servers will won't enjoy having to add a ton of permissions instead of the current singular one

**Comment by BeraTr1** [comment]
Regarding the `bending.command.add.*` perm check, I believe it's already being handled by PK itself. I opened a local server to test it, and `bending.command.add.*` seems to be working as you described. I was able to add all elements and subelements with that perm enabled.

**Comment by JustAHuman-xD** [comment]
> Regarding the `bending.command.add.*` perm check, I believe it's already being handled by PK itself. I opened a local server to test it, and `bending.command.add.*` seems to be working as you described. I was able to add all elements and subelements with that perm enabled.

Ah awesome

**Comment by BeraTr1** [comment]
oops, was messing with these buttons. I've never done a PR before >.>

**Comment by JustAHuman-xD** [comment]
> oops, sorry, didn't mean to request a review. Was messing with these buttons. I've never done a PR before >.>

np!

**Review by ChristopherWMM — DISMISSED** [review]
Thanks for the added permission functionality!

**Review by JustAHuman-xD — APPROVED** [review]

**Comment by BeraTr1** [comment]
Sorry, accidentally made changes to the branch I Pull Requested, and it dismissed the reviews...

**Comment by StrangeOne101** [comment]
Looking at this now, there are firejet and BMC related changes in this PR. Would you prefer to fix the PR or us to just commit the changes?

**Comment by BeraTr1** [comment]
> Looking at this now, there are firejet and BMC related changes in this PR. Would you prefer to fix the PR or us to just commit the changes?

What a mess I've made, sorry! >.>
I'll fix the changes in a few hours.

**Pull request closed without merging**
