### PR TITLE
Cleanup and update files to Java 8

### PR DESCRIPTION
**Pull request by DotDashh**

### CODE REVIEW

**Comment by Loonytoon1997** [comment]
We don't support java 8..

**Comment by DotDashh** [comment]
@Loonytoon1997 Java 7 is EOL.

**Comment by Loonytoon1997** [comment]
All servers use java 7, if we upgrade to java 8 they wouldn't be able to use it

**Comment by DotDashh** [comment]
@Loonytoon1997 That's a big of an exaggeration, plus there's nothing stopping servers from updating.

**Comment by Loonytoon1997** [comment]
The buyers of servers don't control when their host upgrades their java

**Comment by DotDashh** [comment]
@Loonytoon1997 Hosting companies are more than happy to update if requested to.

**Comment by Alex-The-Coder** [comment]
We're not forcing our users to update their java for no reason

**Comment by DotDashh** [comment]
@Alex-The-Coder then how about a separate branch for Java 8?

**Comment by Alex-The-Coder** [comment]
If you want to use it with Java 8, compile it yourself

**Pull request closed without merging**
