### PR TITLE
Display command, Suffocate, & Water Ability Adjustments

### PR DESCRIPTION
**Pull request by xNuminousx**
Just some suggested changes. Am open to revisions/other ideas.

## Additions
* Adds a separate Suffocate animation based on whether the target is in the water or not.
    > * Inspired by #1012 

## Fixes
* Fixed being able to Suffocate ArmorStands
* Fixes WaterArms Spear going through ice blocks.
* Fixes some water abilities from not checking their source block after being selected allowing for players to still use their abilities even if their source has change to a non-waterbendable block.
    > * Issue: #1018 

## Edits
* Removed a redundant "target" variable in Suffocate.
* Moved the entity loop in Suffocates animate() method into progress so that the classic animation and the underwater animation can use the same variable.
* Made the headers for combo and passive displays uniform color rather than using white lettering for the words "Combos" and "Passives".

### CODE REVIEW

**Comment by xNuminousx** [comment]
why does it show my other commits :/

**Comment by ChristopherWMM** [comment]
> why does it show my other commits :/

That would be because you did not rebase from upstream or refork before working on your fork. Don't worry, by squashing your PR it won't have any discernible impact.

**Comment by xNuminousx** [comment]
yea Simp informed me i’d have to reclone when there are new changes

**Comment by xNuminousx** [comment]
the config addition wasn't pushed the first time, but now it is. With the particle fix I also made the stream animation look a bit nicer.

**Comment by Simplicitee** [comment]
> 
> 
> the config addition wasn't pushed the first time, but now it is. With the particle fix I also made the stream animation look a bit nicer.

Can you provide gifs?

**Comment by xNuminousx** [comment]
> > the config addition wasn't pushed the first time, but now it is. With the particle fix I also made the stream animation look a bit nicer.
> 
> Can you provide gifs?

I can try but my gifs aren't really ever that good since my computer isn't the best.

**Comment by xNuminousx** [comment]
Not sure if these links will work so bare with me.

It's a pretty simple and subtle animation, but like I said I am open to suggestions. I can do all sorts of things with it. Hard to get a good representation of the stream since I'm required to be so close to the target, but I tried.
Also, yes I'm testing on armor stands, I turned my check off so that I could test on them. They are the only things that would sit still.

<blockquote class="imgur-embed-pub" lang="en" data-id="zqTy64O"><a href="https://imgur.com/zqTy64O">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

<blockquote class="imgur-embed-pub" lang="en" data-id="g1LFSEZ"><a href="https://imgur.com/g1LFSEZ">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by xNuminousx** [comment]
I've updated the OP to describe all of the contents currently in the PR. Keep in mind, since the last commit I did change the suffocate animation again. I've tried several different swirly or dramatic animations but none seemed right for Suffocate. Currently, Suffocating someone underwater will show bubbles at their mouths but they will appear more intense than before and will increase in particle speed making it a bit more dramatic.

**Comment by xNuminousx** [comment]
> Your adjustments to Torrent, SurgeWave, SurgeWall, IceSpikeBlast, OctopusForm are obsolete.
> 
> ProjectKorra's `BlockSource#getWaterSourceBlock` already checks if they are waterbendable blocks.

Well not in a way that we need them to since the issue existed before I made the changes and now they no longer exist.

**Comment by Varhagna** [comment]
> > Your adjustments to Torrent, SurgeWave, SurgeWall, IceSpikeBlast, OctopusForm are obsolete.
> > ProjectKorra's `BlockSource#getWaterSourceBlock` already checks if they are waterbendable blocks.
> 
> Well not in a way that we need them to since the issue existed before I made the changes and now they no longer exist.

And what exactly was the issue?

**Comment by xNuminousx** [comment]
The source block was defined only once. So when you select your source, the code considers that your source until the ability ends. If someone were to place a block of stone over your grass, the ability would still think that you have grass selected and thus it would allow you to still use your ability even though the grass was gone.

What I've done is put the check on a loop so that the source block is constantly checked for it's waterbendable value. If the source block changes to something that's not waterbendable, it'll remove the ability.

**Comment by xNuminousx** [comment]
Here's an example of what I've changed with the display command:
Before -
Screen Shot 2019-09-07 at 9 05 10 PM
After -
Screen Shot 2019-09-07 at 9 05 17 PM
Full display of the elements -
Screen Shot 2019-09-07 at 9 14 46 PM

**Comment by ChristopherWMM** [comment]
For future reference, I would highly recommend making multiple PR's (this can be achieved by working on one branch per change on your fork) when suggesting so many things at once. It increases the likelihood that each PR will be accepted. I really don't want there to be one thing that stops everything else from being added without a bunch of extra work.

**Comment by xNuminousx** [comment]
> For future reference, I would highly recommend making multiple PR's (this can be achieved by working on one branch per change on your fork) when suggesting so many things at once. It increases the likelihood that each PR will be accepted. I really don't want there to be one thing that stops everything else from being added without a bunch of extra work.

If there's a few things out of the whole PR that won't get accepted just let me know and I'll take them out. But I'll separate it into branch for next time.

**Comment by xNuminousx** [comment]
When I get a free day (which is seemingly going to be never *tear*) I'm going to close this PR and separate it into those different PRs for easier management.

**Comment by Simplicitee** [comment]
Don't worry about that.

**Comment by xNuminousx** [comment]
NPR? *NPE

**Comment by ChristopherWMM** [comment]
I am going to close this because there is too much stuff in it, I would rather have the space to discuss each proposal in its own PR. Please reopen each change you'd like to see happen in its own PR.

**Comment by xNuminousx** [comment]
lol

**Pull request closed without merging**
